export const CHARACTERS: Record<string, unknown> = {
  lyra_dorn: {
    id: "lyra_dorn",
    displayName: "Lyra Dorn",
    title: "Die Jägerin von Fackelruh",
    description: "Präzise Scharfschützin mit Fokus auf kritische Treffer und Markierungen.",
    role: "Interceptor / Duellantin",
    weapon: "Doppelklinge + Funkenpistole",
    vehicleId: "dornwolf",
    theme: "Rache, Überleben, Verantwortung",
    baseStats: { maxHealth: 100, armor: 2, moveSpeedPercent: 110, critChancePercent: 15 },
  },
  mira_voss: {
    id: "mira_voss",
    displayName: "Mira Voss",
    title: "Gelehrte der Sonnenglasweite",
    description: "Unterstützungs-Charakter mit Fokus auf Lore-Entschlüsselung und Schild-Buffs.",
    role: "Controller / Runenbrecherin",
    weapon: "Runenklingen + Archivsigil",
    vehicleId: "archivspinne",
    theme: "Wahrheit, Schuld, Archivmagie",
    baseStats: { maxHealth: 80, armor: 1, moveSpeedPercent: 100, critChancePercent: 5 },
  },
  tarek_al_sahir: {
    id: "tarek_al_sahir",
    displayName: "Tarek Al-Sahir",
    title: "Wüstenwind",
    description: "Mobiler Duelist, der Sand und Glas zur Täuschung nutzt.",
    role: "Skirmisher / Täuscher",
    weapon: "Speer + Spiegelköder",
    vehicleId: "glasfuchs",
    theme: "Schuld, Charme, Flucht und Bindung",
    baseStats: { maxHealth: 90, armor: 3, moveSpeedPercent: 120, critChancePercent: 10 },
  },
  siofra_nhal: {
    id: "siofra_nhal",
    displayName: "Siofra Nhal",
    title: "Wurzelchor-Kind",
    description: "Status-Effekt Spezialistin mit Fokus auf Naturresonanz.",
    role: "Ranger / Fallenbinderin",
    weapon: "Harzbogen + lebende Fallen",
    vehicleId: "moorkäfer",
    theme: "Namen, Erinnerung, Naturresonanz",
    baseStats: { maxHealth: 85, armor: 0, moveSpeedPercent: 105, critChancePercent: 8 },
  },
  brannok_reef: {
    id: "brannok_reef",
    displayName: "Brannok Reef",
    title: "Dammbrecher",
    description: "Heavy Bruiser mit Harpune und Ankerklinge.",
    role: "Bruiser / Harpunierer",
    weapon: "Ankerklinge + Harpune",
    vehicleId: "riffbrecher",
    theme: "Bruder, Sturm, Arbeiterzorn",
    baseStats: { maxHealth: 160, armor: 8, moveSpeedPercent: 85, critChancePercent: 2 },
  },
  edda_falkenlicht: {
    id: "edda_falkenlicht",
    displayName: "Edda Falkenlicht",
    title: "Lichtbringerin",
    description: "Entehrte Adlige mit Fokus auf Schutz und Standarten.",
    role: "Tank / Bannstandarte",
    weapon: "Grossschwert + Eidbanner",
    vehicleId: "eidpanzer",
    theme: "Adel, Pflicht, Gerechtigkeit",
    baseStats: { maxHealth: 120, armor: 10, moveSpeedPercent: 90, critChancePercent: 5 },
  },
  kael_nhar: {
    id: "kael_nhar",
    displayName: "Kael Nhar",
    title: "Schachtflüchtling",
    description: "Assassin mit Dolchen und Schachtgift.",
    role: "Assassin / Debuffer",
    weapon: "Dolche + Schachtgift",
    vehicleId: "schachtmaus",
    theme: "Überleben, Verrat, Opfer",
    baseStats: { maxHealth: 80, armor: 1, moveSpeedPercent: 130, critChancePercent: 20 },
  },
  oren_vale: {
    id: "oren_vale",
    displayName: "Oren Vale",
    title: "Waldläufer / Heiler",
    description: "Barmherziger Heiler-Monk mit Kettenstab.",
    role: "Support / Heiler-Monk",
    weapon: "Kettenstab + Wards",
    vehicleId: "pilgerglocke",
    theme: "Barmherzigkeit ohne Feigheit",
    baseStats: { maxHealth: 100, armor: 4, moveSpeedPercent: 100, critChancePercent: 5 },
  },
  yara_kest: {
    id: "yara_kest",
    displayName: "Yara Kest",
    title: "Kettenhündin / Ingenieurin",
    description: "Technik-Spezialistin mit Schmiedehammer und Drohnen.",
    role: "Engineer / Drohnenkern",
    weapon: "Schmiedehammer + Reparaturdrohne",
    vehicleId: "kranhexe",
    theme: "Arbeit, Erfindung, Aufstand",
    baseStats: { maxHealth: 110, armor: 6, moveSpeedPercent: 95, critChancePercent: 4 },
  },
  neris_vael: {
    id: "neris_vael",
    displayName: "Neris Vael",
    title: "Sturmsängerin / Echo-Magierin",
    description: "Echo-Magierin mit Sichel und Opfermagie.",
    role: "Echo-Mage / Opfermagie",
    weapon: "Sichel + Echoadern",
    vehicleId: "traumsäge",
    theme: "Identität, fremde Erinnerung, Selbstbestimmung",
    baseStats: { maxHealth: 85, armor: 2, moveSpeedPercent: 105, critChancePercent: 10 },
  },
  velka_sturmtritt: {
    id: "velka_sturmtritt",
    displayName: "Velka Sturmtritt",
    title: "Lanzenreiterin / Verfolgerin",
    description: "Gnadenlose Verfolgerin mit Lanze und Sturmleine.",
    role: "Lancer / Verfolgerin",
    weapon: "Lanze + Sturmleine",
    vehicleId: "sturmwidder",
    theme: "Verlust, Professionalität, Zugehörigkeit",
    baseStats: { maxHealth: 130, armor: 8, moveSpeedPercent: 125, critChancePercent: 5 },
  },
  cyr_ohne_gestern: {
    id: "cyr_ohne_gestern",
    displayName: "Cyr Ohne Gestern",
    title: "Das Echo / Adaptive",
    description: "Formwandler, der Techniken kopiert.",
    role: "Adaptive / Formwechsel",
    weapon: "Resonanzwaffe",
    vehicleId: "namenloser_kern",
    theme: "Werkzeug wird Person",
    baseStats: { maxHealth: 100, armor: 5, moveSpeedPercent: 100, critChancePercent: 10 },
  },
  rixa: {
    id: "rixa",
    displayName: "Rixa Chromlilie",
    title: "Alchemistin / Geschwindigkeit",
    description: "Giftmischerin mit Status-Effekt Spezialisierung und extremer Mobilität.",
    role: "Alchemist / DPS",
    weapon: "Funkenpistole + Chromlilien",
    vehicleId: "dornwolf",
    theme: "Chaos, Überlebensfähigkeit, Rausch",
    baseStats: { maxHealth: 90, armor: 1, moveSpeedPercent: 115, critChancePercent: 12 },
  },
  marek: {
    id: "marek",
    displayName: "Marek Schrottanker",
    title: "Tank / Ingenieur",
    description: "Schwerer Panzerer mit Drohnen und Schildgenerierung.",
    role: "Tank / Engineer",
    weapon: "Kettenramme + Drohnenkern",
    vehicleId: "riffbrecher",
    theme: "Schutz, Maschinen, Zugehörigkeit",
    baseStats: { maxHealth: 150, armor: 12, moveSpeedPercent: 80, critChancePercent: 3 },
  },
};
