import { SkillDefinition } from "./schema";

const GENERATED_CHARACTER_IDS: SkillDefinition["characterId"][] = [
  "oren_vale",
  "yara_kest",
  "neris_vael",
  "velka_sturmtritt",
  "cyr_ohne_gestern",
];

export const SKILLS: SkillDefinition[] = [
  // --- LYRA DORN ---
  {
    id: "ab_char_lyra_basic",
    characterId: "lyra_dorn",
    name: "Lyras Grundkette",
    type: "basic",
    input: "M1",
    cooldownMs: 0,
    staminaCost: 0,
    tags: ["basic", "melee"],
    description: "Schnelle Standardkombo, die Ressourcen erzeugt. Spielt schnell, schmutzig, direkt.",
    effects: [{ type: "status", value: 1, statKey: "Mondbrand" }],
    vehicleCompatible: true,
    comboTags: ["Mondbrand"],
  },
  {
    id: "ab_char_lyra_heavy",
    characterId: "lyra_dorn",
    name: "Lyras Brecher",
    type: "technique",
    input: "M2",
    cooldownMs: 4000,
    staminaCost: 0,
    tags: ["heavy", "melee"],
    description: "Langsamer, schwerer Treffer mit hohem Haltungs- und Fahrzeugpanzer-Schaden.",
    effects: [{ type: "status", value: 1, statKey: "Mondbrand" }],
    vehicleCompatible: true,
    comboTags: ["Mondbrand"],
  },
  {
    id: "ab_char_lyra_skill_1",
    characterId: "lyra_dorn",
    name: "Funkenstoss",
    type: "technique",
    input: "Q",
    cooldownMs: 8000,
    staminaCost: 10,
    tags: ["skill", "ranged"],
    description: "Verschiebt Positionen und öffnet ein klares Zeitfenster für Finisher.",
    effects: [{ type: "status", value: 1, statKey: "Mondbrand" }],
    vehicleCompatible: true,
    comboTags: ["Mondbrand"],
  },
  {
    id: "ab_char_lyra_ultimate",
    characterId: "lyra_dorn",
    name: "Hausbrand",
    type: "ultimate",
    input: "R",
    cooldownMs: 90000,
    staminaCost: 0,
    tags: ["ultimate"],
    description: "Verwandelt den persönlichen Konflikt in ein grosses Kampfereignis mit Schadens- und Kontroll-Effekten.",
    effects: [{ type: "aoe_damage", value: 500 }],
    vehicleCompatible: true,
    comboTags: ["Mondbrand"],
  },

  // --- MIRA VOSS ---
  {
    id: "ab_char_mira_basic",
    characterId: "mira_voss",
    name: "Miras Grundkette",
    type: "basic",
    input: "M1",
    cooldownMs: 0,
    staminaCost: 0,
    tags: ["basic", "melee"],
    description: "Spielt kontrolliert, analytisch, gefährlich. Erzeugt Siegelrisse.",
    effects: [{ type: "status", value: 1, statKey: "Siegelriss" }],
    vehicleCompatible: true,
    comboTags: ["Siegelriss"],
  },
  {
    id: "ab_char_mira_skill_1",
    characterId: "mira_voss",
    name: "Siegelbruch",
    type: "technique",
    input: "Q",
    cooldownMs: 8000,
    staminaCost: 10,
    tags: ["skill", "control"],
    description: "Markiert eine Fläche, die Gegner verlangsamt und Mondglas-Illusionen sichtbar macht.",
    effects: [{ type: "status", value: 1, statKey: "Siegelriss" }],
    vehicleCompatible: true,
    comboTags: ["Siegelriss"],
  },

  // --- TAREK AL-SAHIR ---
  {
    id: "ab_char_tarek_basic",
    characterId: "tarek_al_sahir",
    name: "Tareks Grundkette",
    type: "basic",
    input: "M1",
    cooldownMs: 0,
    staminaCost: 0,
    tags: ["basic", "melee"],
    description: "Spielt mobil, täuschend, riskant. Erzeugt Schuldmarken.",
    effects: [{ type: "status", value: 1, statKey: "Schuldmarke" }],
    vehicleCompatible: true,
    comboTags: ["Schuldmarke"],
  },
  {
    id: "ab_char_tarek_skill_1",
    characterId: "tarek_al_sahir",
    name: "Spiegelköder",
    type: "technique",
    input: "Q",
    cooldownMs: 8000,
    staminaCost: 10,
    tags: ["skill", "deception"],
    description: "Erzeugt ein Trugbild, das Angriffe zieht und bei Zerstörung Salzsplitter freisetzt.",
    effects: [{ type: "status", value: 1, statKey: "Schuldmarke" }],
    vehicleCompatible: true,
    comboTags: ["Schuldmarke"],
  },

  // --- SIOFRA NHAL ---
  {
    id: "ab_char_siofra_basic",
    characterId: "siofra_nhal",
    name: "Siofras Grundkette",
    type: "basic",
    input: "M1",
    cooldownMs: 0,
    staminaCost: 0,
    tags: ["basic", "ranged"],
    description: "Spielt präzise, lauernd, organisch. Erzeugt Harzbindung.",
    effects: [{ type: "status", value: 1, statKey: "Harzbindung" }],
    vehicleCompatible: true,
    comboTags: ["Harzbindung"],
  },
  {
    id: "ab_char_siofra_skill_2",
    characterId: "siofra_nhal",
    name: "Wurzelfalle",
    type: "technique",
    input: "E",
    cooldownMs: 12000,
    staminaCost: 20,
    tags: ["skill", "trap"],
    description: "Legt eine klebrige Falle, die Gegner bindet und Verbündete heilt.",
    effects: [{ type: "status", value: 1, statKey: "Harzbindung" }],
    vehicleCompatible: true,
    comboTags: ["Harzbindung"],
  },

  // --- BRANNOK REEF ---
  {
    id: "ab_char_brannok_basic",
    characterId: "brannok_reef",
    name: "Brannoks Grundkette",
    type: "basic",
    input: "M1",
    cooldownMs: 0,
    staminaCost: 0,
    tags: ["basic", "melee"],
    description: "Spielt schwer, laut, brutal ehrlich. Erzeugt Tiefenruf.",
    effects: [{ type: "status", value: 1, statKey: "Tiefenruf" }],
    vehicleCompatible: true,
    comboTags: ["Tiefenruf"],
  },
  {
    id: "ab_char_brannok_skill_1",
    characterId: "brannok_reef",
    name: "Harpunenwurf",
    type: "technique",
    input: "Q",
    cooldownMs: 8000,
    staminaCost: 10,
    tags: ["skill", "pull"],
    description: "Zieht kleine Gegner heran oder katapultiert Brannok zu grossen Gegnern.",
    effects: [{ type: "status", value: 1, statKey: "Tiefenruf" }],
    vehicleCompatible: true,
    comboTags: ["Tiefenruf"],
  },

  // --- EDDA FALKENLICHT ---
  {
    id: "ab_char_edda_basic",
    characterId: "edda_falkenlicht",
    name: "Eddas Grundkette",
    type: "basic",
    input: "M1",
    cooldownMs: 0,
    staminaCost: 0,
    tags: ["basic", "melee"],
    description: "Spielt standhaft, taktisch, ehrenhaft. Erzeugt Eidmarken.",
    effects: [{ type: "status", value: 1, statKey: "Eidmarke" }],
    vehicleCompatible: true,
    comboTags: ["Eidmarke"],
  },
  {
    id: "ab_char_edda_skill_1",
    characterId: "edda_falkenlicht",
    name: "Bannstandarte",
    type: "technique",
    input: "Q",
    cooldownMs: 8000,
    staminaCost: 10,
    tags: ["skill", "protect"],
    description: "Setzt ein Banner, das Verbündete schützt und Eidbrecher-Gegner schwächt.",
    effects: [{ type: "status", value: 1, statKey: "Eidmarke" }],
    vehicleCompatible: true,
    comboTags: ["Eidmarke"],
  },

  // --- KAEL NHAR ---
  {
    id: "ab_char_kael_basic",
    characterId: "kael_nhar",
    name: "Kaels Grundkette",
    type: "basic",
    input: "M1",
    cooldownMs: 0,
    staminaCost: 0,
    tags: ["basic", "melee"],
    description: "Spielt schmutzig, schnell, hinterhältig. Erzeugt Rostbruch.",
    effects: [{ type: "status", value: 1, statKey: "Rostbruch" }],
    vehicleCompatible: true,
    comboTags: ["Rostbruch"],
  },
  {
    id: "ab_char_kael_skill_1",
    characterId: "kael_nhar",
    name: "Schachtdolch",
    type: "technique",
    input: "Q",
    cooldownMs: 8000,
    staminaCost: 10,
    tags: ["skill", "assassin"],
    description: "Schwächt Gegner, die gerade eine Fähigkeit wirken.",
    effects: [{ type: "status", value: 1, statKey: "Rostbruch" }],
    vehicleCompatible: true,
    comboTags: ["Rostbruch"],
  },
  // Adding placeholders for others to maintain count for now
  ...Array.from({ length: 20 }, (_, i): SkillDefinition => ({
    id: `ab_char_other_${i}`,
    characterId: GENERATED_CHARACTER_IDS[i % GENERATED_CHARACTER_IDS.length],
    name: `Generated Skill ${i}`,
    type: "technique",
    input: "E",
    cooldownMs: 5000,
    staminaCost: 10,
    tags: ["generated"],
    description: `A generated skill for testing purposes #${i}`,
    effects: [],
    vehicleCompatible: true,
    comboTags: [],
  })),
];
